version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: BD_Las_Nubes
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "3000"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.6
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
